### PR TITLE
State export import

### LINKED ISSUE #49: PoE Bootstrap from genesis export
When the chain state was exported into a genesis, the (spiked) bootstrap process does not work proper anymore.
The engagement group may need to changed as new validators onboard but the contract state in `wasm` is not updated, the valset contract state may be outdated as validators provide new gentx with new pubkeys. 
🤔  Can the stake contract be outdated?

This includes genesis validation.

Ref https://github.com/confio/tgrade/issues/50

### LINKED ISSUE #50: PoE state export
All modules cosmos-sdk support the state export/ import process where the persistent state data is converted into a json format and used in the (next) genesis file (for a new network) to setup the module again.
Note:
* there may be in-flight data as unclaimed rewards
* slashing and signed block data may be obsolete
* the new validator set may not be the same as the original one
* typically genesis validators are collected via gentx

What else do we need to export?
Contract state is persisted by `wasm` but not easy to read/maintain

### PR DESCRIPTION
**Pull request by alpe**
* Resolves #49 
* Resolves #50 

Based on the #340 spike and #344 

This design comes with a new [`state_exporter_importer`](https://github.com/confio/tgrade/pull/348/files#diff-38c44d2c662951b6fc33e2375623f85b20e3ba70f7c803c9dd407c424f936ef1R45) privilege that allow contracts to register for a custom in state export/import callback.

### Design choices
No support for:
* Zero height exports
* No contract state updates via seed genesis configuration

### Reviewer
Genesis changes #351 are included in this branch, now

A good start would be to follow the code in:
* Model changes in [protobuf](https://github.com/confio/tgrade/pull/348/files#diff-fa6413f9f52f59787bb13d6e40803bb2e6c0d48b9949dcb3faa47910218b4eb8R58)
* Twasm genesis [import/export](https://github.com/confio/tgrade/pull/348/files#diff-963e93cdb0d865b845f9edfcfbfb0a30498609036d3cbe7346a0125b167a2b2bR34)
* PoE genesis [import/export](https://github.com/confio/tgrade/pull/348/files#diff-589972b9e6615f0aff731d96c9a421fa41d539992dc27ecc701f604ccdb69551R30)
* Integration into [app](https://github.com/confio/tgrade/pull/348/files#diff-9bcaf321191d4f6106e27485bdfbbaef716b4e0e4f648d8e5b81a87bc93b6c77R24)

Please do **Squash + Merge**. The single commits do not add value in the history

## Follow up tasks
#356 
#357

### Testing
State export import can be manually tested via:

```sh
# rm -rf ~/.tgrade
./contrib/local/setup_tgrade.sh
./contrib/local/start_node.sh
# run it for some blocks, then ctrl-c to stop the server

# export a state dump
tgrade export --height=-1 > dump.json
# check custom data model for valset contract

# import
tgrade unsafe-reset-all
cp -f dump.json ~/.tgrade/config/genesis.json
./contrib/local/start_node.sh

# check it starts and continues from stopped block
```

### CODE REVIEW

File: app/app_test.go [hunk 1]
```diff
@@ -27,8 +27,6 @@ import (
 var emptyWasmOpts []wasm.Option = nil
 
 func TestTgradeExport(t *testing.T) {
-	t.Skip("Alex, export is not implemented")
```
Comment (ethanfrey) [inline app/app_test.go:30]: 🎉

File: app/app_test.go [hunk 2]
```diff
@@ -78,16 +75,19 @@ func setupWithSingleValidatorGenTX(t *testing.T, genesisState GenesisState) {
 	var bankGenState banktypes.GenesisState
 	marshaler.MustUnmarshalJSON(genesisState[banktypes.ModuleName], &bankGenState)
 
-	coins := sdk.Coins{sdk.NewCoin(poetypes.DefaultBondDenom, sdk.NewInt(1000000000))}
-	bankGenState.Balances = append(bankGenState.Balances, banktypes.Balance{Address: myAddr.String(), Coins: coins.Sort()})
-	bankGenState.Balances = append(bankGenState.Balances, banktypes.Balance{Address: systemAdminAddr.String(), Coins: coins.Sort()})
+	coins := sdk.Coins{sdk.NewCoin(poetypes.DefaultBondDenom, sdk.NewInt(1000000000))}.Sort()
```
Comment (ethanfrey) [inline app/app_test.go:78]: Sort on one coin?

Comment (ethanfrey) [reply app/app_test.go:78]: I guess it is more future proof 🤷‍♂️

File: app/export.go [hunk 3]
```diff
@@ -1,185 +1,89 @@
...
-	//}
-	//
-	//validators, err := staking.WriteValidators(ctx, app.stakingKeeper)
-	//return servertypes.ExportedApp{
-	//	AppState:        appState,
-	//	Validators:      validators,
-	//	Height:          height,
-	//	ConsensusParams: app.BaseApp.GetConsensusParams(ctx),
-	//}, err
+	if forZeroHeight {
```
Comment (ethanfrey) [inline app/export.go:24]: Can you add a comment (or better make a GitHub issue and link to it) about what would be needed to implement this.

We can do it well after mainnet IMO, but as you are working on it, you can best describe the needed work now.

File: app/export.go [hunk 4]
```diff
@@ -1,185 +1,89 @@
...
+	// We export at last height + 1, because that's the height at which
+	// Tendermint will start InitChain.
+	height := app.LastBlockHeight() + 1
+	genState := app.mm.ExportGenesis(ctx, app.appCodec)
+	appState, err := json.MarshalIndent(genState, "", "  ")
+	if err != nil {
+		return servertypes.ExportedApp{}, err
+	}
+
+	validators, err := activeValidatorSet(app, ctx, err)
```
Comment (ethanfrey) [inline app/export.go:40]: :+1:

File: app/genesis_integration_test.go [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+		)
+		gapp.Commit()
+	}
+	memDB := db.NewMemDB()
+	gapp := NewTgradeApp(log.NewTMLogger(log.NewSyncWriter(os.Stdout)), memDB, nil, true, map[int64]bool{}, DefaultNodeHome, 0, MakeEncodingConfig(), EmptyBaseAppOptions{}, emptyWasmOpts)
+	initGenesis := NewDefaultGenesisState()
+
+	doInitWithGenesis(gapp, initGenesis)
+	// Making a new app object with the db, so that initchain hasn't been called
+	newGapp := NewTgradeApp(log.NewTMLogger(log.NewSyncWriter(os.Stdout)), memDB, nil, true, map[int64]bool{}, DefaultNodeHome, 0, MakeEncodingConfig(), EmptyBaseAppOptions{}, emptyWasmOpts)
```
Comment (ethanfrey) [inline app/genesis_integration_test.go:46]: Wait, sharing the same memDB? That looks odd..

Why can't you export with gapp?

(Note, I would make a block or two on app before the export to be a bit more realistic. Even if they are empty or simple bank SendMsg)

File: app/genesis_integration_test.go [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+		}
+	}
+	assert.Equal(t, 1, customModelContractCount)
+
+	// ensure poe is correct
+	var poeGs poetypes.GenesisState
+	require.NoError(t, newGapp.appCodec.UnmarshalJSON(gs[poetypes.ModuleName], &poeGs))
+	require.NoError(t, poetypes.ValidateGenesis(poeGs, MakeEncodingConfig().TxConfig.TxJSONDecoder()))
+	t.Log(string(gs[twasm.ModuleName]))
+	// now import the state on a fresh DB
```
Comment (ethanfrey) [inline app/genesis_integration_test.go:82]: This is the good test if it starts up well.

It would be interesting to have some other state there as well (bank, some instantiated contract) that could be verified by queries. But that can be a separate test, good to have this as basic sanity check

File: x/poe/bootstrap.go [hunk 7]
```diff
@@ -303,14 +302,6 @@ func BootstrapPoEContracts(ctx sdk.Context, k wasmtypes.ContractOpsKeeper, tk tw
 		return sdkerrors.Wrap(err, "set new instance admin")
 	}
 
-	// ensure setup constraints
-	ok, err := tk.HasPrivilegedContract(ctx, stakeContractAddr, twasmtypes.PrivilegeDelegator)
```
Comment (ethanfrey) [inline x/poe/bootstrap.go:307]: Yes, `VerifyPoEContracts` is much better version of this. Nice one

File: x/poe/contract/tgrade_valset.go [hunk 8]
```diff
@@ -402,6 +401,31 @@ func (v ValsetContractAdapter) ListValidators(ctx sdk.Context, pagination *Pagin
...
+		for _, v := range rsp.Validators {
+			if callback(v) {
+				return nil
+			}
+		}
+		newCursor, err := v.doPageableQuery(ctx, ValsetQuery{ListActiveValidators: &ListValidatorsQuery{StartAfter: cursor.String()}}, &rsp)
+		if err != nil {
+			return err
+		}
+		if newCursor.Equal(cursor) {
```
Comment (ethanfrey) [inline x/poe/contract/tgrade_valset.go:421]: Huh? That is an odd check. When do they repeat?

(I thought the `cursor.Empty()` check would be enough)

File: x/poe/contract/tgrade_valset.go [hunk 9]
```diff
@@ -402,6 +401,31 @@ func (v ValsetContractAdapter) ListValidators(ctx sdk.Context, pagination *Pagin
...
+	if err != nil {
+		return err
+	}
+	for !cursor.Empty() {
+		for _, v := range rsp.Validators {
+			if callback(v) {
+				return nil
+			}
+		}
+		newCursor, err := v.doPageableQuery(ctx, ValsetQuery{ListActiveValidators: &ListValidatorsQuery{StartAfter: cursor.String()}}, &rsp)
```
Comment (ethanfrey) [inline x/poe/contract/tgrade_valset.go:417]: Ah, this is the wrong start after. 

It should be `rsp.Validators[len(rsp.Validators)-1].Address` (not 100% on the name of the field, but the address of the last validator returned).

Comment (ethanfrey) [reply x/poe/contract/tgrade_valset.go:417]: Or does the underlying contract not support pagination?

File: x/poe/contract/tgrade_valset_integration_test.go [hunk 10]
```diff
@@ -286,5 +286,33 @@ func TestJailUnjail(t *testing.T) {
...
+		},
+		"list two pages": {
+			valCount: 31,
+		},
+		"list all actives": {
+			valCount: 100,
+		},
+	}
+	for name, spec := range specs {
+		t.Run(name, func(t *testing.T) {
```
Comment (ethanfrey) [inline x/poe/contract/tgrade_valset_integration_test.go:306]: This is not a true test, unless you assert a limit in `IterateActiveValidators` so we know the page size is really 30 (maybe the default is 200?).

File: x/poe/types/genesis.go [hunk 11]
```diff
@@ -145,103 +145,109 @@ func ValidateGenesis(g GenesisState, txJSONDecoder sdk.TxDecoder) error {
...
-	}
-	if _, err := sdk.AccAddressFromBech32(g.SystemAdminAddress); err != nil {
-		return sdkerrors.Wrap(err, "system admin address")
-	}
 
-	uniqueEngagementMembers := make(map[string]struct{}, len(g.Engagement))
-	for i, v := range g.Engagement {
-		if err := v.ValidateBasic(); err != nil {
-			return sdkerrors.Wrapf(err, "contract %d", i)
+		if _, err := sdk.AccAddressFromBech32(g.SystemAdminAddress); err != nil {
```
Comment (ethanfrey) [inline x/poe/types/genesis.go:149]: This is a huge function.

I would make the original check `if g.SeedContracts` call a different function. Maybe one function to validate seed, one non-seed. And before calling either, validate the common parts (params)

File: x/twasm/contract/callback_msgs.go [hunk 12]
```diff
@@ -1,17 +1,26 @@
...
-	/// Block height and time is already in Env
+	// Block height and time is already in Env
 	EndBlock *struct{} `json:"end_block,omitempty"`
-	/// This will be delivered after everything.
-	/// The data in the Response is (JSON?) encoded diff to the validator set
+	// This will be delivered after everything.
+	// The data in the Response is (JSON?) encoded diff to the validator set
 	EndWithValidatorUpdate *struct{} `json:"end_with_validator_update,omitempty"`
+
+	// Export dump state for genesis export
```
Comment (ethanfrey) [inline x/twasm/contract/callback_msgs.go:20]: ah, this gets to the interesting part.

File: x/twasm/contract/callback_msgs.go [hunk 13]
```diff
@@ -1,17 +1,26 @@
...
+	Export *struct{} `json:"export,omitempty"`
+	// Import genesis state
+	Import *wasmtypes.RawContractMessage `json:"import,omitempty"`
```
Comment (ethanfrey) [inline x/twasm/contract/callback_msgs.go:23]: not json.RawMessage?

File: x/twasm/keeper/genesis.go [hunk 14]
```diff
@@ -51,15 +54,25 @@ func InitGenesis(
 		if err := keeper.importPrivileged(ctx, addr, info.CodeID, d); err != nil {
 			return nil, sdkerrors.Wrapf(err, "privilege registration for contract: %s", m.ContractAddress)
 		}
-		importedCallbackContracts[m.ContractAddress] = struct{}{}
+
+		// import custom state when privilege set
+		if d.HasRegisteredPrivilege(types.PrivilegeStateExporterImporter) {
```
Comment (ethanfrey) [inline x/twasm/keeper/genesis.go:59]: nice loop

File: x/twasm/keeper/genesis.go [hunk 15]
```diff
@@ -76,21 +89,55 @@ func InitGenesis(
...
+		contracts[i] = types.Contract{
+			ContractAddress: v.ContractAddress,
+			ContractInfo:    v.ContractInfo,
+		}
+
+		var details types.TgradeContractDetails
+		if err := v.ContractInfo.ReadExtension(&details); err != nil {
+			panic(fmt.Sprintf("read contract info extension for %s", v.ContractAddress))
+		}
+		if !details.HasRegisteredPrivilege(types.PrivilegeStateExporterImporter) {
```
Comment (ethanfrey) [inline x/twasm/keeper/genesis.go:109]: Nice default behavior

File: x/twasm/keeper/genesis.go [hunk 16]
```diff
@@ -76,21 +89,55 @@ func InitGenesis(
...
+		}
+		c, err := sdk.AccAddressFromBech32(v.ContractAddress)
+		if err != nil {
+			panic(fmt.Sprintf("address %s: %s", v.ContractAddress, err))
+		}
+		bz, err := json.Marshal(contract.TgradeSudoMsg{Export: &struct{}{}})
+		if err != nil {
+			panic(sdkerrors.Wrapf(err, "marshal state export for %s", c.String()))
+		}
+		got, err := keeper.Keeper.Sudo(ctx, c, bz)
```
Comment (ethanfrey) [inline x/twasm/keeper/genesis.go:121]: And custom behaviour :+1:

File: x/twasm/types/codec.go [hunk 17]
```diff
@@ -13,6 +13,7 @@ func RegisterLegacyAminoCodec(cdc *codec.LegacyAmino) {
 	wasmtypes.RegisterLegacyAminoCodec(cdc)
 	cdc.RegisterConcrete(&PromoteToPrivilegedContractProposal{}, "twasm/PromoteToPrivilegedContractProposal", nil)
 	cdc.RegisterConcrete(&DemotePrivilegedContractProposal{}, "twasm/DemotePrivilegedContractProposal", nil)
+	cdc.RegisterConcrete(&TgradeContractDetails{}, "twasm/TgradeContractDetails", nil)
```
Comment (ethanfrey) [inline x/twasm/types/codec.go:16]: no more amino, please 😢 

(I know you have to do it, but these lines hurt when I see it still there)

File: x/twasm/types/genesis.go [hunk 18]
```diff
@@ -60,3 +64,46 @@ func (g GenesisState) ValidateBasic() error {
 
 	return nil
 }
+
+// RawWasmState convert to wasm genesis state for vanilla import.
+// Custom data models for privileged contracts are not included
+func (g GenesisState) RawWasmState() wasmtypes.GenesisState {
```
Comment (ethanfrey) [inline x/twasm/types/genesis.go:70]: This is mainly for fixtures (and as empty case for InitGenesis), right?

**Review by ethanfrey — APPROVED** [review]
Nice Work! 🏅 

I left a number of comments showing my thinking and areas that stood out to me as well. If you review them / answer them and are content with it, no need to wait another approval from me. 

I didn't look at go style, just the business logic.

File: app/app_test.go (hunk 2 above)
Comment (alpe) [reply app/app_test.go:78]: haha, good eye. Will remove this.

File: app/export.go (hunk 3 above)
Comment (alpe) [reply app/export.go:24]: 👍  added https://github.com/confio/tgrade/issues/356

File: app/genesis_integration_test.go (hunk 6 above)
Comment (alpe) [reply app/genesis_integration_test.go:82]: AFAIK this is done via simulations in `TestAppImportExport`, although not supported in this branch.

File: x/poe/contract/tgrade_valset.go (hunk 9 above)
Comment (alpe) [reply x/poe/contract/tgrade_valset.go:417]: @maurolacy can you double check my code please?

File: x/poe/contract/tgrade_valset_integration_test.go (hunk 10 above)
Comment (alpe) [reply x/poe/contract/tgrade_valset_integration_test.go:306]: Correct! I verified though that it returns 30 as default but there is no guarantee for the future. I went forth and back with adding a limit to the query or not. Later, I removed it to rely on the contract developers work and design choice.
I give it another thought now. Thanks for finding this!

File: x/poe/types/genesis.go (hunk 11 above)
Comment (alpe) [reply x/poe/types/genesis.go:149]: done in the other branch already

File: x/twasm/contract/callback_msgs.go (hunk 13 above)
Comment (alpe) [reply x/twasm/contract/callback_msgs.go:23]: I want to be consistent with wasmd here. We use this type with other contract messages. it serializes into raw json.

File: x/poe/contract/tgrade_valset.go (hunk 9 above)
Comment (maurolacy) [reply x/poe/contract/tgrade_valset.go:420]: Taking a look now.

Comment (maurolacy) [reply x/poe/contract/tgrade_valset.go:420]: This is correct AFAIK. It's a little tricky with the pagination cursor, but this code is similar / equivalent to the one in `TestListAllValidatorsViaCursor` integration test (it just uses the `doPageableQuery` wrapper).

The cursor is a copy of some of the last elements of the page (the operator address).

**Review by maurolacy — APPROVED** [review]
LGTM. Great work.

Didn't review everything to the detail, as it's a really long PR, but followed your "review path" suggestion.

**Review by pinosu — APPROVED** [review]
lgtm 🥇 excellent work!
