### PR TITLE
Handle double signing

### LINKED ISSUE #187: Test double sign protection
As a system test in CI if possible (not too hard)

Otherwise, let's just run this once manually to ensure it works.

### LINKED ISSUE #232: Fix begin block callback to valset
Intentionally double signed:
```
ERR begin block contract failed cause="Error parsing into type tg_bindings::sudo::TgradeSudoMsg: unknown variant `DuplicateVote`, expected `duplicate_vote` or `light_client_attack`: execute wasm contract failed" contract-address=tgrade1pvrwmjuusn9wh34j7y520g8gumuy9xtl2ne37x module=x/wasm position=1
```

### PR DESCRIPTION
**Pull request by alpe**
Resolves #187 
Resolves #232 

Classic multi project integration error 🤦

### CODE REVIEW

File: x/twasm/contract/callback_msgs.go [hunk 1]
```diff
@@ -31,8 +31,10 @@ type BeginBlock struct {
 
 type EvidenceType string
 
-const EvidenceDuplicateVote EvidenceType = "DuplicateVote"
-const EvidenceLightClientAttack EvidenceType = "LightClientAttack"
+const (
```
Comment (ethanfrey) [inline x/twasm/contract/callback_msgs.go:34]: Ah, these were defined improperly in Go, but work in Rust?

Of course, the [auto-snake-casing](https://github.com/confio/poe-contracts/blob/main/packages/bindings/src/sudo.rs#L47-L65)

Glad you tested this and good fix.

**Review by ethanfrey — APPROVED** [review]
lgtm

**Comment by alpe** [comment]
Do not merge before #226  is fixed so that I can tag v0.5.3 on master
